apiVersion: apps/v1
kind: Deployment
metadata:
  name: third-deployment
  labels:
    app: thirddep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thirddep
  template:
    metadata:
      labels:
        app: thirddep
    spec:
      containers:
        - name: thirddep
          imagePullPolicy: "IfNotPresent"
          image: assignment
          ports:
          - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: third-service
spec:
  type: NodePort
  selector:
    app: thirddep
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000